### ISSUE TITLE
Ruby gems Backup and VSCode

### ISSUE THREAD

**Issue by AlexanderProd** [alichtman/shallow-backup#204]
Just opening up this issue as feature request for backing up Ruby Gems and VSCode settings and extensions. 

I'll post the relevant directories after I figured them out.

**Comment by AlexanderProd** [comment]
Closed issues because Ruby Gems are already being backuped and there's already an Issue for VSCode.

**Comment by alichtman** [comment]
> Ruby Gems are already being backuped

Not correctly, though. #38 is open, and isn't something I'll end up fixing because I don't use Ruby too much, so if you want to work out the issue and open a PR, that'd be great. 

> VSCode

#45 is open already for this, and it should just be a change in the default config file in `config.py`. PR would also be appreciated here.
