### ISSUE TITLE
You should try asciinema instead of upload big GIF file demo

### ISSUE THREAD

**Issue by balalaXD** [alichtman/shallow-backup#222]
Look at [asciinema](https://asciinema.org/)

**Comment by alichtman** [comment]
I used to have an asciinema demo instead of a GIF, but I opted for the GIF so it would autoplay on the page. 

The only reasons to use asciinema are: 

1. Optimize load-time of the page 
2. Be considerate of data usage if the person is on a metered connection

Honestly, I think the GIF looks nice, and I definitely don't have time to redo it, so, that's sorta where I'll leave this.
