### ISSUE TITLE
Cannot interactively set backup path to existing backup repo

### ISSUE THREAD

**Issue by ThatsJustCheesy** [alichtman/shallow-backup#266]
In light of #265 I tried to move my backup dir, but the interactive prompt refuses to do it:

<img width="528" alt="Screen Shot 2020-04-22 at 5 58 36 PM" src="https://user-images.githubusercontent.com/16456186/80038102-e5ac0800-84c2-11ea-89c2-cd4d984d39cc.png">

Is this because it always wants to initialize a new git repo on "first run"? In any case, it would be nice to have an interactive way to move the backup like this. Or maybe there is somehow; if that's the case it would be helpful to say how after the red error message.

(I know I can manually edit the config, but the rest of the UI is so nice and free of JSON editing!)

Thanks!

**Comment by alichtman** [comment]
The reason this is failing is actually by design.

Updating the path in the CLI **moves** the directory for you, which you did in the `$ mv` command. It's saying "Hey, you already have a directory in the place you just asked me to set up the shallow-backup repo. I'm not going to do that just in case you didn't want to overwrite this directory."

The simple fix is to move your repo back to the location specified in the config and then move it in the CLI.

The CLI could have a better indication that this is what happens. Maybe "Would you like to update this? (This will move the directory x to y)` or something would be a better prompt.

**Comment by ThatsJustCheesy** [comment]
Sure, I'll take a stab at it tomorrow. I don't do much Python though so you'll have to bear with me a bit 😅

**Comment by alichtman** [comment]
I'm happy to provide any code reviewing / help you need. This should just be a simple string change, so a great intro-to-python issue.
