### ISSUE TITLE
Backup Terminal Preferences from .plist file

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#48]
1. Back up this file.
2. Copy it back to this location in the `-reinstall` command. 

`/Users/alichtman/Library/Preferences/com.apple.Terminal.plist`

**Comment by schilli91** [comment]
I noticed that you store also the sublime text configs, when performing the dotfiles backup. That is why I would also backup the terminal plist file in this mode.
However, I think there should be an extra mode "-app_settings" that handles such backups. Also, this feature should be an extra issue, since it is in fact a completely new feature.

Is there a way yet to reinstall dotfiles? If I'm not completely mistaken, as of now it's only possible to reinstall the packages right?
This is why I'm not sure if a reinstall functionality should be provided for the plist file, because now it would be treated as a dotfile.
Of course when adding the new app_settings mode, the reinstall method should/could be added.

What do you think, @alichtman?

**Comment by alichtman** [comment]
>  think there should be an extra mode `-app_settings` that handles such backups.

How about `-configs` that would back up app and system configs? So, sublime text settings as well as terminal settings, etc.

> Is there a way yet to reinstall dotfiles? If I'm not completely mistaken, as of now it's only possible to reinstall the packages right?

You're right, this is currently not a feature, but it should be. Reinstalling dotfiles should be as easy as copying over the files into the user's home directory.
