### ISSUE TITLE
Currently shallow backup writes to directory ./DEFAULT/ if you don't choose a custom directory

### ISSUE THREAD

**Issue by jasikpark** [alichtman/shallow-backup#93]
If you run `shallow-backup` with the currrent latest version on Github, the default directory that it backs up to is `./DEFAULT`, or `~/DEFAULT` since I ran it in my home directory. 

Should this not be a more intuitive `./shallow-backups` or something more descriptive?

**Comment by alichtman** [comment]
Fixed on master -- update your branch.

**Comment by jasikpark** [comment]
My fork is even with master and it still does this.

**Comment by alichtman** [comment]
Hmm. I'll take a look at this when I have free time (by this weekend for
sure)

On Oct 18, 2018 11:19 AM, "Caleb Jasik" <notifications@github.com> wrote:

My fork is even with master and it still does this.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/alichtman/shallow-backup/issues/93#issuecomment-431072421>,
or mute the thread

**Comment by jasikpark** [comment]
It would appear that `get_default_config()` returns `DEFAULT` for `backup_path`. 

![9252696c-f3df-4bd8-bef5-fb4c932f6c5b](https://user-images.githubusercontent.com/10626596/47170075-c713f200-d2ca-11e8-8796-ad365986d787.png)

**Comment by alichtman** [comment]
Oh, right. `backup_path` should be `""`, not DEFAULT.

**Comment by alichtman** [comment]
Fixed.
